services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:8080"
  server:
    build:
      context: server
    container_name: golang_app
    ports:
      - "8082:8082"